/**
 * 施工方案 JSON Schema 定义 — 用于结构化输出约束和完整性校验
 */

export interface PlanChapterSchema {
  name: string;
  required: boolean;
  autoGenerated: boolean;      // 是否可100%自动生成
  keywords: string[];           // 完整性检测关键词
  minLength: number;            // 最少字符数
  standards: string[];          // 关联标准条款
}

export interface PlanSchema {
  type: string;
  chapters: PlanChapterSchema[];
}

/** 施工组织设计 Schema */
export const ConstructionOrgSchema: PlanSchema = {
  type: '施工组织设计',
  chapters: [
    { name: '编制依据', required: true, autoGenerated: true, keywords: ['依据', '标准', '规范', 'DB', 'GB'], minLength: 200, standards: ['DB11/T695-2025'] },
    { name: '工程概况', required: true, autoGenerated: false, keywords: ['概况', '规模', '地点', '投资'], minLength: 300, standards: [] },
    { name: '施工部署', required: true, autoGenerated: false, keywords: ['部署', '组织', '流水', '分区'], minLength: 500, standards: [] },
    { name: '施工进度计划', required: true, autoGenerated: false, keywords: ['进度', '工期', '节点', '里程碑'], minLength: 300, standards: [] },
    { name: '施工准备与资源配置', required: true, autoGenerated: false, keywords: ['准备', '资源', '人员', '机械', '材料'], minLength: 300, standards: [] },
    { name: '主要施工方法', required: true, autoGenerated: false, keywords: ['方法', '工艺', '流程', '技术'], minLength: 500, standards: [] },
    { name: '质量管理措施', required: true, autoGenerated: false, keywords: ['质量', '验收', '检测', '控制'], minLength: 300, standards: ['GB50300'] },
    { name: '安全管理措施', required: true, autoGenerated: true, keywords: ['安全', '防护', '危险', '事故'], minLength: 300, standards: ['JGJ59'] },
    { name: '文明施工与环境保护', required: true, autoGenerated: true, keywords: ['文明', '环保', '扬尘', '噪音'], minLength: 200, standards: ['DB11/T695-2025'] },
    { name: '应急预案', required: true, autoGenerated: true, keywords: ['应急', '预案', '救援', '演练'], minLength: 200, standards: [] },
  ],
};

/** 深基坑方案 Schema */
export const DeepExcavationSchema: PlanSchema = {
  type: '深基坑专项方案',
  chapters: [
    { name: '编制依据', required: true, autoGenerated: true, keywords: ['依据', '标准', '规范'], minLength: 200, standards: ['JGJ120', 'DB11/T695-2025'] },
    { name: '工程概况', required: true, autoGenerated: false, keywords: ['概况', '深度', '地质', '水位'], minLength: 300, standards: [] },
    { name: '支护方案', required: true, autoGenerated: false, keywords: ['支护', '围护', '锚杆', '支撑'], minLength: 500, standards: ['JGJ120'] },
    { name: '降水方案', required: true, autoGenerated: false, keywords: ['降水', '排水', '止水', '帷幕'], minLength: 400, standards: [] },
    { name: '土方开挖', required: true, autoGenerated: false, keywords: ['开挖', '分层', '出土', '运输'], minLength: 300, standards: [] },
    { name: '监测方案', required: true, autoGenerated: false, keywords: ['监测', '变形', '沉降', '预警'], minLength: 300, standards: ['JGJ120'] },
    { name: '安全管理措施', required: true, autoGenerated: true, keywords: ['安全', '防护', '危险'], minLength: 300, standards: ['JGJ59'] },
    { name: '应急预案', required: true, autoGenerated: true, keywords: ['应急', '救援', '塌方', '涌水'], minLength: 200, standards: [] },
  ],
};

/** 获取方案Schema */
export function getPlanSchema(type: string): PlanSchema | null {
  if (type.includes('施工组织设计')) return ConstructionOrgSchema;
  if (type.includes('深基坑')) return DeepExcavationSchema;
  return ConstructionOrgSchema; // 默认
}

/** 完整性校验 */
export interface CompletenessReport {
  total: number;
  passed: number;
  warnings: { chapter: string; issue: string; severity: 'error' | 'warn' }[];
  score: number;
}

export function checkCompleteness(chapters: { name: string; content: string }[], schema: PlanSchema): CompletenessReport {
  const report: CompletenessReport = { total: schema.chapters.length, passed: 0, warnings: [], score: 0 };
  for (const sc of schema.chapters) {
    const ch = chapters.find(c => c.name === sc.name);
    if (!ch) {
      report.warnings.push({ chapter: sc.name, issue: `缺失章节: ${sc.name}`, severity: 'error' });
      continue;
    }
    if (!ch.content || ch.content.trim().length < 10) {
      report.warnings.push({ chapter: sc.name, issue: `章节内容为空`, severity: 'error' });
      continue;
    }
    if (sc.minLength && ch.content.length < sc.minLength) {
      report.warnings.push({ chapter: sc.name, issue: `内容偏短(${ch.content.length}字, 建议≥${sc.minLength}字)`, severity: 'warn' });
    }
    const missingKw = sc.keywords.filter(k => !ch.content.includes(k));
    if (missingKw.length > 2) {
      report.warnings.push({ chapter: sc.name, issue: `可能缺少关键内容: ${missingKw.join(', ')}`, severity: 'warn' });
    }
    report.passed++;
  }
  report.score = Math.round((report.passed / report.total) * 100);
  return report;
}

/** JSON Schema 约束 — 用于LLM结构化输出 */
export const REVIEW_JSON_SCHEMA = `{
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "section": { "type": "string", "description": "审查的章节名称" },
      "status": { "type": "string", "enum": ["pass", "warn", "fail"] },
      "standard": { "type": "string", "description": "引用的标准条文编号" },
      "comment": { "type": "string", "description": "审查意见" }
    },
    "required": ["section", "status", "standard", "comment"]
  }
}`;
